language: cpp

compiler:
  - clang
  - gcc

addons:
  sonarcloud:
    organization: "ferzerkerx-github"
    token:
      secure: "I6EDQJoENrY/ky2fEbxXtKKc8hrxhg1J3cQWHzmUrLHFeEzpU9Vk4XSnCOmG11BZNh5MUr6P9SRUT/05bxWeHLSrC8q7b1Z9B6S9SdEZapiACsFW2H6jfQ4KcWFjvu6GtDxHRqUuDPuqdGPdh7tQbBCYKrsUKALkzdA+EHPewXmJilGNWtSUWPz2Fc1omSv8NTO1iP9YMAccga6tsfpvbNTdBdrN9rMfaE6PnXduhRjclzc1fwZK23qiLv+2ED1vCfdFrYRbbfIHtrRaLVjMDzUKSqXP6Dv5M3HTiFtZs7qN1UQYHMAx2628n0F+rl5BWvjym/is5wVc1ZRri2cT4WsXJwNZZvju0XxKPODBIc534aWS5Yu5mynbZx24I1/Ab+g3/m8xNml3VWXQTLJUesbDDCWRQn4/n79NqKrY85ipCczveg2KVPjBbghLzI1Ze0MnxfTSp4h5KUPHam6ynC+5+pXSD44YYCRA6NhbxXvsLaGfiSP41iVaIolXtINoSbwZ2vTqN68A/EhzcV49eLYVnzOqBAFGoi5BscMOdujz9Eqgcf3qsoKuKi/v6UZPcZ2OmhAl983fl+jpGV+cYkgtMdCfo9GtzdtvMTk9xMGD5/lyAeGthccl24bKcmfvGd2dxMxDzg/KT647CxOVr8qPO3QrtMLwtI2CDlpVUCk="

install: make get-deps

script: echo 'Done'
